version: "3.9"
services:
  pokemon-frontend:
    container_name: frontend
    build: '../pokemon-frontend'
    ports:
    - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT

  mysqldb:
    container_name: mysql-warehouse
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_WAREHOUSE_LOCAL_PORT:$MYSQLDB_WAREHOUSE_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  warehouse:
    container_name: warehouse
    depends_on:
      - mysqldb
    build: '../warehouse/pokemon-app'
    env_file: ./.env
    ports:
      - $WAREHOUSE_LOCAL_PORT:$WAREHOUSE_DOCKER_PORT
    expose:
      - 8081
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  api-gateway:
    container_name: api-gateway
    build: '../api-gateway'
    ports:
      - $API_GATEWAY_LOCAL_PORT:$API_GATEWAY_DOCKER_PORT

  product-service:
    container_name: product-service
    depends_on:
      - mysqldb-product
    build: '../product-service'
    ports:
      - $PRODUCT_LOCAL_PORT:$PRODUCT_DOCKER_PORT
    volumes:
      - .m2:/root/.m2


  mysqldb-product:
    container_name: mysql-product
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PRODUCT_LOCAL_PORT:$MYSQLDB_PRODUCT_DOCKER_PORT
    volumes:
      - db-product:/var/lib/mysql

  rabbitmq:
    container_name: rabbitMQ
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  db:
  db-product:
