version: "3.9"
services:
  pokemon-frontend:
    container_name: frontend
    build: '../frontend'
    ports:
    - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
    command: redis-server
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.0
    ports:
      - $KEYCLOAK_LOCAL_PORT:$KEYCLOAK_DOCKER_PORT
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev

  mysqldb:
    container_name: warehouse-mysql
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_WAREHOUSE_LOCAL_PORT:$MYSQLDB_WAREHOUSE_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  warehouse:
    container_name: warehouse
    depends_on:
      - mysqldb
    build: '../warehouse/pokemon-app'
    env_file: ./.env
    ports:
      - $WAREHOUSE_LOCAL_PORT:$WAREHOUSE_DOCKER_PORT
    expose:
      - 8081
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  api-gateway:
    container_name: api-gateway
    build: '../api-gateway'
    ports:
      - $API_GATEWAY_LOCAL_PORT:$API_GATEWAY_DOCKER_PORT

  mysqldb-product:
    container_name: product-mysql
    image: mysql:5.7
    depends_on:
      - warehouse
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PRODUCT_LOCAL_PORT:$MYSQLDB_PRODUCT_DOCKER_PORT
    volumes:
      - db-product:/var/lib/mysql

  product-service:
    container_name: product-service
    depends_on:
      - mysqldb-product
    build: '../product-service'
    ports:
      - $PRODUCT_LOCAL_PORT:$PRODUCT_DOCKER_PORT
    volumes:
      - .m2:/root/.m2

  rabbitmq:
    container_name: rabbitMQ
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  currency-service:
    container_name: currency-service
    depends_on:
      - rabbitmq
    build: '../currency-service'

  price-service:
    container_name: price-service
    depends_on:
      - rabbitmq
    build: '../price-service'



volumes:
  db:
  db-product:
